// Ages 6–7 · Year 2 · Grade 2
export default {
  id: 'adventurers', name: 'Adventurers', ages: '6–7', grade: 'Year 2 · Grade 2', emoji: '🚀', color: '#3B82F6',
  about: 'Bossy-r sounds, choosing the right spelling, endings, compound words, contractions and tenses.',
  levels: [
    { id: 'bossyr', title: 'Bossy R', blurb: 'ar, or, er sounds', emoji: '🦖', engine: 'TapAll',
      content: { rounds: [
        { prompt: 'Tap every word with the sound', target: 'ar', clip: 'ar', say: 'ar', items: [
          { w: 'car', ok: true }, { w: 'star', ok: true }, { w: 'farm', ok: true }, { w: 'park', ok: true }, { w: 'fork', ok: false }, { w: 'bird', ok: false } ],
          explain: 'When r comes after a vowel it is “bossy” and changes the vowel’s sound: c-ar.' },
        { prompt: 'Tap every word with the sound', target: 'or', clip: 'or', say: 'or', hint: 'or, aw or au', items: [
          { w: 'fork', ok: true }, { w: 'horse', ok: true }, { w: 'saw', ok: true }, { w: 'sauce', ok: true }, { w: 'shark', ok: false }, { w: 'girl', ok: false } ],
          explain: 'or, aw and au can all make the same sound: fork, saw, sauce.' },
        { prompt: 'Tap every word with the sound', target: 'er', clip: 'er', say: 'er', hint: 'er, ir or ur', items: [
          { w: 'her', ok: true }, { w: 'bird', ok: true }, { w: 'fur', ok: true }, { w: 'nurse', ok: true }, { w: 'corn', ok: false }, { w: 'jar', ok: false } ],
          explain: 'er, ir and ur all sound the same — that’s why spelling them is tricky!' },
      ] } },
    { id: 'whichspell', title: 'Which Spelling?', blurb: 'ai or ay? ee or ea?', emoji: '🔍', engine: 'Choose',
      content: { prompt: 'Pick the spelling that makes the right word', keepOrder: true, rounds: [
        { emoji: '🌧️', sentence: ['r', 'n'], options: ['ai', 'ay', 'a_e'], answer: 'ai', say: 'rain', explain: 'ai usually sits in the MIDDLE of a word: rain, train, snail.' },
        { emoji: '🎮', sentence: ['pl', ''], options: ['ai', 'ay', 'a_e'], answer: 'ay', say: 'play', explain: 'ay usually sits at the END of a word: play, day, say.' },
        { emoji: '⛵', sentence: ['b', 't'], options: ['oa', 'ow', 'o_e'], answer: 'oa', say: 'boat', explain: 'oa usually goes in the middle: boat, coat, road.' },
        { emoji: '❄️', sentence: ['sn', ''], options: ['oa', 'ow', 'o_e'], answer: 'ow', say: 'snow', explain: 'ow often goes at the end: snow, grow, slow.' },
        { emoji: '🌳', sentence: ['tr', ''], options: ['ee', 'ea', 'ey'], answer: 'ee', say: 'tree' },
        { emoji: '🍃', sentence: ['l', 'f'], options: ['ee', 'ea', 'ey'], answer: 'ea', say: 'leaf' },
        { emoji: '🌙', sentence: ['n', 't'], options: ['igh', 'ie', 'i_e'], answer: 'igh', say: 'night', explain: 'igh is three letters making one sound: n-igh-t.' },
        { emoji: '🪙', sentence: ['c', 'n'], options: ['oi', 'oy'], answer: 'oi', say: 'coin', explain: 'oi in the middle (coin), oy at the end (boy).' },
        { emoji: '👦', sentence: ['b', ''], options: ['oi', 'oy'], answer: 'oy', say: 'boy' },
      ] } },
    { id: 'clap', title: 'Clap the Beats', blurb: 'Count syllables', emoji: '👏', engine: 'Clap',
      content: { words: [
        { word: 'rabbit', parts: ['rab', 'bit'], emoji: '🐰' },
        { word: 'pencil', parts: ['pen', 'cil'], emoji: '✏️' },
        { word: 'sandwich', parts: ['sand', 'wich'], emoji: '🥪' },
        { word: 'butterfly', parts: ['but', 'ter', 'fly'], emoji: '🦋' },
        { word: 'banana', parts: ['ba', 'na', 'na'], emoji: '🍌' },
        { word: 'computer', parts: ['com', 'pu', 'ter'], emoji: '💻' },
        { word: 'crocodile', parts: ['croc', 'o', 'dile'], emoji: '🐊' },
        { word: 'caterpillar', parts: ['cat', 'er', 'pil', 'lar'], emoji: '🐛' },
      ] } },
    { id: 'endings', title: 'Add an Ending', blurb: '-s -es -ing -ed -ful -ly', emoji: '🔚', engine: 'Transform',
      content: { prompt: 'Add the ending to make a new word', items: [
        { parts: ['cat', 's'], result: 'cats', emoji: '🐱🐱', explain: 'Add -s to make more than one.' },
        { parts: ['fox', 'es'], result: 'foxes', emoji: '🦊🦊', explain: 'Words ending in x, s, sh or ch take -es: foxes, buses, wishes, lunches.' },
        { parts: ['wish', 'es'], result: 'wishes', emoji: '🌠' },
        { parts: ['jump', 'ing'], result: 'jumping', emoji: '🤸', explain: '-ing means it is happening now.' },
        { parts: ['play', 'ed'], result: 'played', emoji: '⚽', explain: '-ed means it already happened.' },
        { parts: ['help', 'ful'], result: 'helpful', emoji: '🤝', explain: '-ful means “full of”: helpful = full of help.' },
        { parts: ['quick', 'ly'], result: 'quickly', emoji: '🐇', explain: '-ly tells us HOW something is done.' },
        { parts: ['sad', 'ness'], result: 'sadness', emoji: '😢', explain: '-ness turns a describing word into a thing: sad → sadness.' },
      ] } },
    { id: 'compound', title: 'Compound Words', blurb: 'sun + flower', emoji: '🌻', engine: 'Transform',
      content: { prompt: 'Two words join to make one new word!', items: [
        { parts: ['sun', 'flower'], result: 'sunflower', emoji: '🌻' },
        { parts: ['rain', 'bow'], result: 'rainbow', emoji: '🌈' },
        { parts: ['foot', 'ball'], result: 'football', emoji: '⚽' },
        { parts: ['tooth', 'brush'], result: 'toothbrush', emoji: '🪥' },
        { parts: ['star', 'fish'], result: 'starfish', emoji: '⭐' },
        { parts: ['pan', 'cake'], result: 'pancake', emoji: '🥞' },
        { parts: ['snow', 'man'], result: 'snowman', emoji: '⛄' },
        { parts: ['butter', 'fly'], result: 'butterfly', emoji: '🦋', explain: 'A butterfly isn’t made of butter — compound words can be silly!' },
      ] } },
    { id: 'wordjobs', title: 'Word Jobs', blurb: 'Naming, doing, describing', emoji: '🏷️', engine: 'TapAll',
      content: { rounds: [
        { prompt: 'Tap every NOUN (naming word)', hint: 'a person, animal, place or thing', items: [
          { w: 'dog', ok: true }, { w: 'school', ok: true }, { w: 'teacher', ok: true }, { w: 'ball', ok: true }, { w: 'run', ok: false }, { w: 'happy', ok: false } ],
          explain: 'Nouns name things. Try putting “the” in front: the dog, the school.' },
        { prompt: 'Tap every VERB (doing word)', hint: 'something you can do', items: [
          { w: 'jump', ok: true }, { w: 'sing', ok: true }, { w: 'eat', ok: true }, { w: 'swim', ok: true }, { w: 'cat', ok: false }, { w: 'tall', ok: false } ],
          explain: 'Verbs are actions. Try putting “I can” in front: I can jump.' },
        { prompt: 'Tap every ADJECTIVE (describing word)', hint: 'tells us more about a noun', items: [
          { w: 'tiny', ok: true }, { w: 'red', ok: true }, { w: 'fluffy', ok: true }, { w: 'loud', ok: true }, { w: 'bird', ok: false }, { w: 'read', ok: false } ],
          explain: 'Adjectives describe nouns: a tiny, fluffy kitten.' },
      ] } },
    { id: 'sentencetypes', title: 'Sentence Types', blurb: '. ? !', emoji: '❗', engine: 'Choose',
      content: { prompt: 'Which mark ends this sentence?', keepOrder: true, rounds: [
        { emoji: '🌤️', text: 'The sky is blue', options: ['.', '?', '!'], answer: '.', say: 'The sky is blue.', explain: 'A statement tells you something. It ends with a full stop.' },
        { emoji: '❓', text: 'What is your name', options: ['.', '?', '!'], answer: '?', say: 'What is your name?', explain: 'A question asks something. It ends with a question mark.' },
        { emoji: '😲', text: 'Watch out', options: ['.', '?', '!'], answer: '!', say: 'Watch out!', explain: 'An exclamation shows strong feeling. It ends with !' },
        { emoji: '🧭', text: 'Where are you going', options: ['.', '?', '!'], answer: '?', say: 'Where are you going?' },
        { emoji: '🍦', text: 'I like ice cream', options: ['.', '?', '!'], answer: '.', say: 'I like ice cream.' },
        { emoji: '🏆', text: 'What a great goal', options: ['.', '?', '!'], answer: '!', say: 'What a great goal!', explain: '“What a…” and “How…” sentences that show feeling are exclamations.' },
      ] } },
    { id: 'contractions', title: 'Squash Words', blurb: "do not → don't", emoji: '🤏', engine: 'Transform',
      content: { prompt: 'Squash two words together with an apostrophe', items: [
        { parts: ['do', 'not'], result: "don't", emoji: '🙅', explain: "The apostrophe ’ shows where the o in “not” is missing." },
        { parts: ['I', 'am'], result: "I'm", emoji: '🙋', explain: "I am → I'm. The a is missing." },
        { parts: ['can', 'not'], result: "can't", emoji: '🚫' },
        { parts: ['it', 'is'], result: "it's", emoji: '👉', explain: "it is → it's. (its without an apostrophe means “belonging to it”.)" },
        { parts: ['we', 'will'], result: "we'll", emoji: '👫' },
        { parts: ['she', 'is'], result: "she's", emoji: '👧' },
        { parts: ['they', 'are'], result: "they're", emoji: '👨‍👩‍👧' },
      ] } },
    { id: 'tense', title: 'Then & Now', blurb: 'Past and present', emoji: '⏰', engine: 'Choose',
      content: { prompt: 'Choose the word that fits', rounds: [
        { emoji: '🛝', sentence: ['Yesterday I ', ' to the park.'], options: ['walk', 'walked', 'walking'], answer: 'walked', explain: '“Yesterday” means the past, so we add -ed.' },
        { emoji: '🐕', sentence: ['Look! The dog is ', '.'], options: ['run', 'ran', 'running'], answer: 'running', explain: '“is …ing” means it is happening right now.' },
        { emoji: '🍕', sentence: ['Last night we ', ' pizza.'], options: ['eat', 'eated', 'ate'], answer: 'ate', explain: 'Some verbs are rule-breakers: eat → ate, not “eated”.' },
        { emoji: '🎒', sentence: ['Every day she ', ' to school.'], options: ['walks', 'walked', 'walking'], answer: 'walks' },
        { emoji: '🚲', sentence: ['Yesterday he ', ' his bike.'], options: ['rided', 'rode', 'ride'], answer: 'rode', explain: 'ride → rode is another rule-breaker.' },
        { emoji: '🏊', sentence: ['Tomorrow we ', ' go swimming.'], options: ['will', 'did', 'was'], answer: 'will', explain: '“will” talks about the future.' },
      ] } },
  ],
}
