// Ages 7–9 · Years 3–4 · Grades 3–4
export default {
  id: 'champions', name: 'Champions', ages: '7–9', grade: 'Years 3–4 · Grades 3–4', emoji: '🏆', color: '#F97316',
  about: 'Prefixes, suffix spelling rules, plurals, sound-alikes, apostrophes, speech marks and joining words.',
  levels: [
    { id: 'prefixes', title: 'Prefix Power', blurb: 'un- dis- mis- re- sub-', emoji: '🔧', engine: 'Transform',
      content: { prompt: 'A prefix goes at the START and changes the meaning', items: [
        { parts: ['un', 'happy'], result: 'unhappy', emoji: '😟', explain: 'un- means NOT: unhappy = not happy.' },
        { parts: ['dis', 'agree'], result: 'disagree', emoji: '🙅', explain: 'dis- means the opposite: disagree.' },
        { parts: ['mis', 'spell'], result: 'misspell', emoji: '✏️', explain: 'mis- means wrongly. Keep BOTH s’s: mis + spell = misspell.' },
        { parts: ['re', 'build'], result: 'rebuild', emoji: '🧱', explain: 're- means again: rebuild = build again.' },
        { parts: ['sub', 'marine'], result: 'submarine', emoji: '🚢', explain: 'sub- means under: a submarine goes under the sea.' },
        { parts: ['super', 'hero'], result: 'superhero', emoji: '🦸', explain: 'super- means above or more than.' },
        { parts: ['auto', 'graph'], result: 'autograph', emoji: '✍️', explain: 'auto- means self: an autograph is your own signature.' },
        { parts: ['in', 'visible'], result: 'invisible', emoji: '👻', explain: 'in- can also mean not: invisible = can’t be seen.' },
      ] } },
    { id: 'suffixrules', title: 'Suffix Rules', blurb: 'hopping, making, happier', emoji: '📜', engine: 'Transform',
      content: { prompt: 'Which spelling is right?', items: [
        { parts: ['hop', 'ing'], result: 'hopping', options: ['hoping', 'hopping', 'hopeing'], emoji: '🐇', explain: 'Short vowel + one consonant? DOUBLE it: hop → hopping.' },
        { parts: ['make', 'ing'], result: 'making', options: ['makeing', 'making', 'makking'], emoji: '🧁', explain: 'Ends in silent e? DROP the e: make → making.' },
        { parts: ['happy', 'er'], result: 'happier', options: ['happyer', 'happier', 'happyier'], emoji: '😄', explain: 'Consonant + y? Change y to i: happy → happier.' },
        { parts: ['run', 'er'], result: 'runner', options: ['runer', 'runner', 'runnr'], emoji: '🏃', explain: 'Doubling rule again: run → runner.' },
        { parts: ['smile', 'ed'], result: 'smiled', options: ['smileed', 'smiled', 'smilled'], emoji: '😊', explain: 'Drop the e: smile → smiled.' },
        { parts: ['carry', 'ed'], result: 'carried', options: ['carryed', 'carried', 'carrid'], emoji: '📦', explain: 'y → i: carry → carried.' },
        { parts: ['swim', 'ing'], result: 'swimming', options: ['swiming', 'swimming', 'swimeing'], emoji: '🏊' },
        { parts: ['play', 'ed'], result: 'played', options: ['plaied', 'played', 'playd'], emoji: '🎮', explain: 'Vowel + y? Keep the y: play → played.' },
      ] } },
    { id: 'plurals', title: 'More Than One', blurb: 'foxes, mice, children', emoji: '🐭', engine: 'Choose',
      content: { prompt: 'One… two… what’s the plural?', rounds: [
        { emoji: '🦊', sentence: ['one fox, two ', ''], options: ['foxs', 'foxes', 'foxies'], answer: 'foxes', explain: 'Words ending in x add -es.' },
        { emoji: '👶', sentence: ['one baby, two ', ''], options: ['babys', 'babies', 'babyes'], answer: 'babies', explain: 'Consonant + y → change y to i and add -es.' },
        { emoji: '🍂', sentence: ['one leaf, two ', ''], options: ['leafs', 'leaves', 'leafes'], answer: 'leaves', explain: 'Many words ending in f change to -ves: leaf → leaves.' },
        { emoji: '🐭', sentence: ['one mouse, two ', ''], options: ['mouses', 'mice', 'mices'], answer: 'mice', explain: 'A rule-breaker! mouse → mice.' },
        { emoji: '🧒', sentence: ['one child, two ', ''], options: ['childs', 'children', 'childrens'], answer: 'children' },
        { emoji: '🐑', sentence: ['one sheep, two ', ''], options: ['sheeps', 'sheep', 'sheepes'], answer: 'sheep', explain: 'Some words stay the same: one sheep, ten sheep!' },
        { emoji: '🦷', sentence: ['one tooth, two ', ''], options: ['tooths', 'teeth', 'teeths'], answer: 'teeth' },
        { emoji: '🔪', sentence: ['one knife, two ', ''], options: ['knifes', 'knives', 'knifs'], answer: 'knives' },
      ] } },
    { id: 'homophones', title: 'Sound-Alikes', blurb: 'to, too, two & friends', emoji: '👂', engine: 'Choose',
      content: { prompt: 'They sound the same — which spelling fits?', rounds: [
        { emoji: '🏪', sentence: ['I went ', ' the shop.'], options: ['to', 'too', 'two'], answer: 'to' },
        { emoji: '🐱🐱', sentence: ['I have ', ' cats.'], options: ['to', 'too', 'two'], answer: 'two', explain: 'two is the number 2.' },
        { emoji: '🙋', sentence: ['Can I come ', '?'], options: ['to', 'too', 'two'], answer: 'too', explain: 'too means “also” or “very” (too hot!).' },
        { emoji: '👉', sentence: ['Look over ', '!'], options: ['there', 'their', "they're"], answer: 'there', explain: 'there is a place — it has “here” inside it!' },
        { emoji: '👧👦', sentence: ['It is ', ' turn.'], options: ['there', 'their', "they're"], answer: 'their', explain: 'their means belonging to them.' },
        { emoji: '⏰', sentence: ['', ' going to be late.'], options: ['There', 'Their', "They're"], answer: "They're", explain: "They're = they are." },
        { emoji: '🎒', sentence: ['Is this ', ' bag?'], options: ['your', "you're"], answer: 'your', explain: "you're = you are. your = belonging to you." },
        { emoji: '🐦', sentence: ['I can ', ' the birds singing.'], options: ['hear', 'here'], answer: 'hear', explain: 'You hear with your EAR — it’s inside the word!' },
        { emoji: '🌊', sentence: ['We swam in the ', '.'], options: ['see', 'sea'], answer: 'sea' },
        { emoji: '✍️', sentence: ['Please ', ' your name.'], options: ['write', 'right'], answer: 'write' },
      ] } },
    { id: 'apostrophes', title: 'Whose Is It?', blurb: "Sam's, girls', children's", emoji: '🎁', engine: 'Choose',
      content: { prompt: 'Pick the correct apostrophe', rounds: [
        { emoji: '⚽', sentence: ['This is ', ' ball.'], options: ["Sam's", 'Sams', "Sams'"], answer: "Sam's", explain: "One owner: add 's → Sam's ball." },
        { emoji: '🐈', sentence: ['The ', ' tail is fluffy.'], options: ["cat's", 'cats', "cats'"], answer: "cat's", explain: "One cat owns the tail: cat's." },
        { emoji: '🧥', sentence: ['All the ', ' coats were wet.'], options: ["girl's", "girls'", 'girls'], answer: "girls'", explain: "Many girls (girls) own the coats: put the apostrophe after the s → girls'." },
        { emoji: '🧸', sentence: ['The ', ' toys were everywhere.'], options: ["children's", "childrens'", 'childrens'], answer: "children's", explain: "children doesn’t end in s, so add 's: children's." },
        { emoji: '👟', sentence: ['I ', ' find my shoe.'], options: ["can't", 'cant', "ca'nt"], answer: "can't", explain: 'The apostrophe goes where letters are missing: can not → can’t.' },
        { emoji: '🐕', sentence: ['The dog wagged ', ' tail.'], options: ['its', "it's"], answer: 'its', explain: "its (no apostrophe) = belonging to it. it's = it is." },
      ] } },
    { id: 'synonyms', title: 'Same or Opposite', blurb: 'Synonyms & antonyms', emoji: '🔁', engine: 'Choose',
      content: { prompt: 'Read carefully: SAME or OPPOSITE?', rounds: [
        { q: 'Which word means the SAME as big?', text: 'big', options: ['huge', 'tiny', 'red'], answer: 'huge', explain: 'Words with the same meaning are synonyms.' },
        { q: 'Which word means the SAME as happy?', text: 'happy', options: ['glad', 'sad', 'cross'], answer: 'glad' },
        { q: 'Which word means the SAME as quick?', text: 'quick', options: ['fast', 'slow', 'late'], answer: 'fast' },
        { q: 'Which word means the SAME as shout?', text: 'shout', options: ['yell', 'whisper', 'sleep'], answer: 'yell' },
        { q: 'Which word means the OPPOSITE of hot?', text: 'hot', options: ['cold', 'warm', 'sunny'], answer: 'cold', explain: 'Words with opposite meanings are antonyms.' },
        { q: 'Which word means the OPPOSITE of full?', text: 'full', options: ['empty', 'heavy', 'round'], answer: 'empty' },
        { q: 'Which word means the OPPOSITE of ancient?', text: 'ancient', options: ['modern', 'old', 'broken'], answer: 'modern' },
        { q: 'Which word means the OPPOSITE of brave?', text: 'brave', options: ['timid', 'bold', 'strong'], answer: 'timid' },
      ] } },
    { id: 'speech', title: 'Speech Marks', blurb: '“Who said that?”', emoji: '💬', engine: 'Choose',
      content: { prompt: 'Which one uses speech marks correctly?', rounds: [
        { options: ['"Come here," said Mum.', 'Come here, said Mum.', '"Come here" said Mum.'], answer: '"Come here," said Mum.', explain: 'Speech marks go around the spoken words, with the comma INSIDE them.' },
        { options: ['"Where is my hat?" asked Tom.', '"Where is my hat" asked Tom?', 'Where is my hat? asked Tom.'], answer: '"Where is my hat?" asked Tom.', explain: 'The question mark belongs to the spoken words, so it goes inside.' },
        { options: ['Sara shouted, "Watch out!"', 'Sara shouted "Watch out!"', 'Sara shouted, Watch out!'], answer: 'Sara shouted, "Watch out!"', explain: 'When the speaker comes first, put a comma before the speech marks.' },
        { options: ['"I like cake," said Ben.', '"I like cake." said Ben.', 'I like cake," said Ben.'], answer: '"I like cake," said Ben.' },
        { options: ['"Let\'s go!" cried Ava.', '"Let\'s go"! cried Ava.', 'Let\'s go! "cried Ava."'], answer: '"Let\'s go!" cried Ava.' },
      ] } },
    { id: 'conjunctions', title: 'Joining Words', blurb: 'and, but, so, because', emoji: '🔗', engine: 'Choose',
      content: { prompt: 'Pick the best joining word (conjunction)', rounds: [
        { emoji: '🌧️', sentence: ['I wanted to play outside ', ' it was raining.'], options: ['and', 'but', 'so'], answer: 'but', explain: '“but” shows a contrast — something didn’t go to plan.' },
        { emoji: '🥪', sentence: ['I was hungry ', ' I made a sandwich.'], options: ['so', 'but', 'or'], answer: 'so', explain: '“so” shows a result.' },
        { emoji: '🧥', sentence: ['We stayed inside ', ' it was cold.'], options: ['because', 'or', 'but'], answer: 'because', explain: '“because” gives a reason.' },
        { emoji: '🥛', sentence: ['Would you like milk ', ' juice?'], options: ['or', 'so', 'because'], answer: 'or', explain: '“or” gives a choice.' },
        { emoji: '🪥', sentence: ['I brush my teeth ', ' I go to bed.'], options: ['before', 'or', 'but'], answer: 'before', explain: '“before”, “after” and “when” tell us about time.' },
        { emoji: '🏅', sentence: ['She was happy ', ' she won the race.'], options: ['because', 'or', 'but'], answer: 'because' },
      ] } },
    { id: 'adverbs', title: 'How, When, Where', blurb: 'Adverbs', emoji: '🏎️', engine: 'TapAll',
      content: { rounds: [
        { prompt: 'Tap the adverbs that tell us HOW', hint: 'many end in -ly', items: [
          { w: 'quickly', ok: true }, { w: 'slowly', ok: true }, { w: 'loudly', ok: true }, { w: 'happily', ok: true }, { w: 'dog', ok: false }, { w: 'jump', ok: false } ],
          explain: 'Adverbs tell us more about a verb: she ran QUICKLY.' },
        { prompt: 'Tap the adverbs that tell us WHEN', items: [
          { w: 'yesterday', ok: true }, { w: 'soon', ok: true }, { w: 'today', ok: true }, { w: 'later', ok: true }, { w: 'table', ok: false }, { w: 'green', ok: false } ] },
        { prompt: 'Tap the adverbs that tell us WHERE', items: [
          { w: 'outside', ok: true }, { w: 'here', ok: true }, { w: 'everywhere', ok: true }, { w: 'upstairs', ok: true }, { w: 'quickly', ok: false }, { w: 'cat', ok: false } ] },
      ] } },
    { id: 'spelltest', title: 'Spelling Challenge', blurb: 'Year 3–4 tricky words', emoji: '📝', engine: 'SpellIt',
      content: { mode: 'hidden', words: [
        { word: 'answer', hint: 'The w is silent! What is the ___?' },
        { word: 'build', hint: 'Let’s ___ a den. (u is silent)' },
        { word: 'busy', hint: 'The shop was very ___. (u says “i”)' },
        { word: 'heart', hint: 'It beats in your chest. (ea says “ar”)' },
        { word: 'guard', hint: 'A soldier on ___. (silent u)' },
        { word: 'breath', hint: 'Take a deep ___.' },
        { word: 'often', hint: 'I ___ go to the park.' },
        { word: 'library', hint: 'A place full of books. Say it: li-brar-y.' },
      ] } },
  ],
}
