// Ages 9–11 · Years 5–6 · Grades 5–6
export default {
  id: 'masters', name: 'Masters', ages: '9–11', grade: 'Years 5–6 · Grades 5–6', emoji: '👑', color: '#8B5CF6',
  about: 'Tricky spelling patterns, silent letters, Greek & Latin roots, clauses, commas and figurative language.',
  levels: [
    { id: 'ieei', title: 'i before e?', blurb: 'receive, believe, weird', emoji: '🔤', engine: 'Choose',
      content: { prompt: 'ie or ei?', keepOrder: true, rounds: [
        { sentence: ['bel', 've'], options: ['ie', 'ei'], answer: 'ie', say: 'believe', explain: 'The rule: i before e…' },
        { sentence: ['rec', 've'], options: ['ie', 'ei'], answer: 'ei', say: 'receive', explain: '…except after c: receive, ceiling.' },
        { sentence: ['f', 'ld'], options: ['ie', 'ei'], answer: 'ie', say: 'field' },
        { sentence: ['c', 'ling'], options: ['ie', 'ei'], answer: 'ei', say: 'ceiling', explain: 'After c again — so e comes first.' },
        { sentence: ['fr', 'nd'], options: ['ie', 'ei'], answer: 'ie', say: 'friend' },
        { sentence: ['n', 'ghbour'], options: ['ie', 'ei'], answer: 'ei', say: 'neighbour', explain: 'When it sounds like “ay”, it’s ei: neighbour, eight, weigh.' },
        { sentence: ['w', 'rd'], options: ['ie', 'ei'], answer: 'ei', say: 'weird', explain: '“weird” is weird — it breaks the rule! Just remember it.' },
        { sentence: ['th', 'f'], options: ['ie', 'ei'], answer: 'ie', say: 'thief' },
      ] } },
    { id: 'tion', title: '-tion, -sion, -cian', blurb: 'action, television, musician', emoji: '🎼', engine: 'Choose',
      content: { prompt: 'Which ending completes the word?', keepOrder: true, rounds: [
        { sentence: ['ac', ''], options: ['tion', 'sion', 'cian'], answer: 'tion', say: 'action', explain: '-tion is the most common “shun” ending.' },
        { sentence: ['televi', ''], options: ['tion', 'sion', 'cian'], answer: 'sion', say: 'television', explain: '-sion often follows d or s in the root: televise → television.' },
        { sentence: ['musi', ''], options: ['tion', 'sion', 'cian'], answer: 'cian', say: 'musician', explain: '-cian is for PEOPLE and jobs: music → musician.' },
        { sentence: ['explo', ''], options: ['tion', 'sion', 'cian'], answer: 'sion', say: 'explosion', explain: 'explode → explosion (d becomes s).' },
        { sentence: ['electri', ''], options: ['tion', 'sion', 'cian'], answer: 'cian', say: 'electrician' },
        { sentence: ['posi', ''], options: ['tion', 'sion', 'cian'], answer: 'tion', say: 'position' },
        { sentence: ['deci', ''], options: ['tion', 'sion', 'cian'], answer: 'sion', say: 'decision', explain: 'decide → decision.' },
        { sentence: ['magi', ''], options: ['tion', 'sion', 'cian'], answer: 'cian', say: 'magician' },
      ] } },
    { id: 'silent', title: 'Silent Letters', blurb: 'knight, lamb, island', emoji: '🤫', engine: 'Choose',
      content: { prompt: 'Which letter is silent?', keepOrder: true, rounds: [
        { text: 'knight', options: ['k', 'n', 't'], answer: 'k', say: 'knight', explain: 'kn at the start: the k is silent (knee, knock, know).' },
        { text: 'write', options: ['w', 'r', 't'], answer: 'w', say: 'write', explain: 'wr at the start: the w is silent (wrong, wrist).' },
        { text: 'lamb', options: ['l', 'm', 'b'], answer: 'b', say: 'lamb', explain: 'mb at the end: the b is silent (thumb, climb, comb).' },
        { text: 'island', options: ['i', 's', 'd'], answer: 's', say: 'island' },
        { text: 'castle', options: ['c', 's', 't'], answer: 't', say: 'castle', explain: 'stle: the t is silent (whistle, listen).' },
        { text: 'gnome', options: ['g', 'n', 'm'], answer: 'g', say: 'gnome', explain: 'gn at the start: the g is silent (gnaw, gnat).' },
        { text: 'honest', options: ['h', 'n', 't'], answer: 'h', say: 'honest', explain: 'Some words start with a silent h: honest, hour.' },
        { text: 'thumb', options: ['t', 'm', 'b'], answer: 'b', say: 'thumb' },
      ] } },
    { id: 'ableible', title: '-able or -ible?', blurb: 'enjoyable, possible', emoji: '🧩', engine: 'Choose',
      content: { prompt: 'Which ending is right?', keepOrder: true, rounds: [
        { sentence: ['comfort', ''], options: ['able', 'ible'], answer: 'able', say: 'comfortable', explain: 'Tip: if the root is a whole word (comfort), it’s usually -able.' },
        { sentence: ['poss', ''], options: ['able', 'ible'], answer: 'ible', say: 'possible', explain: '“poss” isn’t a word on its own, so it’s usually -ible.' },
        { sentence: ['enjoy', ''], options: ['able', 'ible'], answer: 'able', say: 'enjoyable' },
        { sentence: ['vis', ''], options: ['able', 'ible'], answer: 'ible', say: 'visible' },
        { sentence: ['reli', ''], options: ['able', 'ible'], answer: 'able', say: 'reliable', explain: 'rely → reliable: y changes to i, then -able.' },
        { sentence: ['horr', ''], options: ['able', 'ible'], answer: 'ible', say: 'horrible' },
        { sentence: ['break', ''], options: ['able', 'ible'], answer: 'able', say: 'breakable' },
        { sentence: ['sens', ''], options: ['able', 'ible'], answer: 'ible', say: 'sensible' },
      ] } },
    { id: 'roots', title: 'Word Roots', blurb: 'Greek & Latin building blocks', emoji: '🏛️', engine: 'Choose',
      content: { prompt: 'Roots carry meaning. What does this one mean?', rounds: [
        { q: 'tele — as in telephone, television', text: 'tele', options: ['far', 'water', 'life'], answer: 'far', explain: 'tele (Greek) = far. A telescope sees far away.' },
        { q: 'bio — as in biology, biography', text: 'bio', options: ['life', 'small', 'sound'], answer: 'life', explain: 'bio = life. Biology is the study of living things.' },
        { q: 'aqua — as in aquarium, aquatic', text: 'aqua', options: ['water', 'air', 'light'], answer: 'water' },
        { q: 'micro — as in microscope, microphone', text: 'micro', options: ['small', 'big', 'far'], answer: 'small', explain: 'micro = small. A microscope makes tiny things look big.' },
        { q: 'graph — as in autograph, paragraph', text: 'graph', options: ['write', 'see', 'carry'], answer: 'write' },
        { q: 'port — as in transport, portable', text: 'port', options: ['carry', 'look', 'break'], answer: 'carry', explain: 'port (Latin) = carry. Portable means you can carry it.' },
        { q: 'phon — as in phonics, microphone', text: 'phon', options: ['sound', 'light', 'life'], answer: 'sound' },
        { q: 'spect — as in inspect, spectator', text: 'spect', options: ['look', 'write', 'water'], answer: 'look', explain: 'spect = look. A spectator watches.' },
      ] } },
    { id: 'classes', title: 'Word Classes', blurb: 'Pronouns, prepositions, conjunctions', emoji: '🗃️', engine: 'TapAll',
      content: { rounds: [
        { prompt: 'Tap every PRONOUN', hint: 'words that stand in for a noun', items: [
          { w: 'she', ok: true }, { w: 'they', ok: true }, { w: 'it', ok: true }, { w: 'we', ok: true }, { w: 'table', ok: false }, { w: 'run', ok: false } ],
          explain: 'Pronouns replace nouns so we don’t repeat them: Mia ran → SHE ran.' },
        { prompt: 'Tap every PREPOSITION', hint: 'shows where or when', items: [
          { w: 'under', ok: true }, { w: 'behind', ok: true }, { w: 'between', ok: true }, { w: 'during', ok: true }, { w: 'quickly', ok: false }, { w: 'apple', ok: false } ],
          explain: 'Prepositions link nouns to other words: under the bed, during lunch.' },
        { prompt: 'Tap every CONJUNCTION', hint: 'joins words or clauses', items: [
          { w: 'and', ok: true }, { w: 'because', ok: true }, { w: 'although', ok: true }, { w: 'unless', ok: true }, { w: 'jump', ok: false }, { w: 'red', ok: false } ] },
      ] } },
    { id: 'commas', title: 'Comma Sense', blurb: 'Clauses & fronted adverbials', emoji: '✒️', engine: 'Choose',
      content: { prompt: 'Which sentence uses commas correctly?', rounds: [
        { options: ['After lunch, we played football.', 'After, lunch we played football.', 'After lunch we, played football.'], answer: 'After lunch, we played football.', explain: 'A fronted adverbial (“After lunch”) is followed by a comma.' },
        { options: ['I bought apples, pears, bananas and grapes.', 'I bought, apples pears bananas and grapes.', 'I bought apples pears, bananas, and, grapes.'], answer: 'I bought apples, pears, bananas and grapes.', explain: 'Commas separate items in a list.' },
        { options: ['My sister, who loves cats, has three pets.', 'My sister who, loves cats has three pets.', 'My, sister who loves cats, has three pets.'], answer: 'My sister, who loves cats, has three pets.', explain: 'Commas go around an extra-information clause (a relative clause).' },
        { options: ['Slowly, the tortoise crossed the road.', 'Slowly the, tortoise crossed the road.', 'Slowly the tortoise, crossed the road.'], answer: 'Slowly, the tortoise crossed the road.' },
        { options: ['Yes, I would love to come.', 'Yes I would, love to come.', 'Yes I, would love to come.'], answer: 'Yes, I would love to come.' },
        { options: ['Although it rained, we had fun.', 'Although, it rained we had fun.', 'Although it rained we, had fun.'], answer: 'Although it rained, we had fun.', explain: 'When a sentence starts with a subordinate clause, put a comma after it.' },
      ] } },
    { id: 'figurative', title: 'Figurative Language', blurb: 'Simile, metaphor & more', emoji: '🎨', engine: 'Choose',
      content: { prompt: 'What kind of language is this?', keepOrder: true, rounds: [
        { text: 'as brave as a lion', options: ['Simile', 'Metaphor', 'Personification', 'Alliteration'], answer: 'Simile', explain: 'A simile compares using “as” or “like”.' },
        { text: 'The wind whispered through the trees.', options: ['Simile', 'Metaphor', 'Personification', 'Alliteration'], answer: 'Personification', explain: 'Personification gives human actions to things — wind can’t really whisper!' },
        { text: 'Sally sells seashells by the seashore.', options: ['Simile', 'Metaphor', 'Personification', 'Alliteration'], answer: 'Alliteration', explain: 'Alliteration repeats the same starting sound.' },
        { text: 'Time is a thief.', options: ['Simile', 'Metaphor', 'Personification', 'Alliteration'], answer: 'Metaphor', explain: 'A metaphor says something IS something else.' },
        { text: 'as cold as ice', options: ['Simile', 'Metaphor', 'Personification', 'Alliteration'], answer: 'Simile' },
        { text: 'The stars danced in the sky.', options: ['Simile', 'Metaphor', 'Personification', 'Alliteration'], answer: 'Personification' },
        { text: 'My brother is a couch potato.', options: ['Simile', 'Metaphor', 'Personification', 'Alliteration'], answer: 'Metaphor' },
        { text: 'Big bears bounce on blue balloons.', options: ['Simile', 'Metaphor', 'Personification', 'Alliteration'], answer: 'Alliteration' },
      ] } },
    { id: 'spelltest', title: 'Spelling Challenge', blurb: 'Year 5–6 tricky words', emoji: '📝', engine: 'SpellIt',
      content: { mode: 'hidden', words: [
        { word: 'rhythm', hint: 'The beat in music. (no vowels except y!)' },
        { word: 'yacht', hint: 'A fancy sailing boat. (ch is silent)' },
        { word: 'queue', hint: 'A line of people waiting. (ueue!)' },
        { word: 'muscle', hint: 'It helps your body move. (silent c)' },
        { word: 'soldier', hint: 'Someone in the army. (di says “j”)' },
        { word: 'vehicle', hint: 'A car, bus or van. (silent h)' },
        { word: 'ancient', hint: 'Very, very old. (ci says “sh”)' },
        { word: 'island', hint: 'Land with water all around. (silent s)' },
      ] } },
  ],
}
